### ISSUE TITLE
[BUG] (Enter your description here)WingetUI newst will not install winget:?

### ISSUE THREAD

**Issue by PeterWalter8769** [marticliment/UniGetUI#2911] opened 2024-10-29 18:43 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows Pro 24h2 26100.2161

### Describe your issue

WingetUI will not intall winget: what to do?

### Steps to reproduce the issue

anytime

### UniGetUI Log

```text
name=PowerShell
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -Command Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
Working Directory      : C:\Users\profp


Process Start Time     : 29.10.2024 19:41:39
Update-Module : Es wurde kein Parameter gefunden, der dem Parameternamen "Scope" entspricht.
In Zeile:1 Zeichen:68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
Process Exit Code      : 1
```

### Package Managers Logs

```text
no log
```

### Relevant information

non

### Screenshots and videos

non

**Comment by marticliment** [comment] 2024-10-29 21:03
Duplicate of #2903

**Closed by marticliment** 2024-10-29 21:03 UTC
Labels: bug
