### ISSUE TITLE
[BUG] 3.10 Final tries to install 3.10 beta 1

### ISSUE THREAD

**Issue by DrStrange** [marticliment/UniGetUI#2400] opened 2024-07-03 09:50 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 Final

### Windows version, edition and architecture

Windows 10 22H2 10.0.19045.4598

### Describe your issue

3.1.0 Final tries but fails to "update" to 3.1.0-beta1. I presume this is because winget option is set as `RunAsAdministrator=False` or that UnigetUI won't alllow itself to be updated when it's running, but I don't know why it's trying to install an older version. I didn't have this issue with 3.1.0-beta2. I have set UnigetUI to ignore this previous version. Hopefully this version will disappear as time goes on so will not be offered as an update in the future.
I am using the preview version v1.9.1792 of winget.

### UniGetUI Log

```text
[03/07/24 10:34:58] 
                       __  __      _ ______     __  __  ______
                      / / / /___  (_) ____/__  / /_/ / / /  _/
                     / / / / __ \/ / / __/ _ \/ __/ / / // /  
                    / /_/ / / / / / /_/ /  __/ /_/ /_/ // /   
                    \____/_/ /_/_/\____/\___/\__/\____/___/   
                        Welcome to UniGetUI Version 3.1.0
[03/07/24 10:34:58]
[03/07/24 10:34:58] Version Code:  3.1
[03/07/24 10:34:58] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[03/07/24 10:34:59] Loaded language locale: en
[03/07/24 10:34:59] Randomly-generated background API auth token for the current session: icvl8u92g2e2kv2mvn8306qzzrrz7rgdfuuddjqrduvsass3vozok6qimwo955tj
[03/07/24 10:34:59] Api running on http://localhost:7058
[03/07/24 10:34:59] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Chocolatey
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:34:59] Lang files were updated successfully from GitHub
[03/07/24 10:35:00] UniGetUI is up to date
[03/07/24 10:35:00] Command npm was not found on the system
[03/07/24 10:35:00] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Npm
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:35:02] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Pip
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: pip
                    █ Executable path: C:\Program Files\Python312\python.exe
                    █ Call arguments:  -m pip
                    █ Version: 
                    █   pip 24.1.1 from C:\Users\Susan\AppData\Roaming\Python\Python312\site-packages\pip (python 3.12)
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:35:02] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: .NET Tool
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:35:02] Downloaded new icons and screenshots successfully!
[03/07/24 10:35:02] Command scoop was not found on the system
[03/07/24 10:35:02] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Scoop
                    █ Enabled: False
                    █ THE MANAGER IS DISABLED
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:35:04] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: Winget
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: winget.exe
                    █ Executable path: C:\Users\Susan\AppData\Local\Microsoft\WindowsApps\winget.exe
                    █ Call arguments: 
                    █ Version: 
                    █   Naive WinGet CLI Version: v1.9.1792-preview
                    █   Microsoft.WinGet.Client PSModule version: 
                    █   Using Native WinGet helper (COM Api)
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:35:06] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                    █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                    █ Name: PowerShell
                    █ Enabled: True
                    █ Found: True
                    █ Fancye exe name: powershell.exe
                    █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                    █ Call arguments:  -NoProfile -Command
                    █ Version: 
                    █   Name                           Value                                                                                   
                    █   ----                           -----                                                                                   
                    █   PSVersion                      5.1.19041.4597                                                                          
                    █   PSEdition                      Desktop                                                                                 
                    █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                    █   BuildVersion                   10.0.19041.4597                                                                         
                    █   CLRVersion                     4.0.30319.42000                                                                         
                    █   WSManStackVersion              3.0                                                                                     
                    █   PSRemotingProtocolVersion      2.3                                                                                     
                    █   SerializationVersion           1.1.0.1
                    ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[03/07/24 10:35:07] Resetting administrator rights cache for process id 12220
[03/07/24 10:35:10] Found 1 installed packages from Pip
[03/07/24 10:35:12] Found 0 available updates from Pip
[03/07/24 10:35:15] Dependency WinGet PowerShell Module for manager Winget is present
[03/07/24 10:35:15] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[03/07/24 10:35:16] Found 2 installed packages from PowerShell
[03/07/24 10:35:21] Found 2 available updates from Winget
[03/07/24 10:35:21] Found 0 available updates from PowerShell
[03/07/24 10:35:21] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[03/07/24 10:35:21] Icon for package SomePythonThings.WingetUIStore.Pre-release was not found, returning default icon
[03/07/24 10:35:21] Found 185 installed packages from Winget
[03/07/24 10:35:29] Resetting administrator rights cache for process id 12220
[03/07/24 10:36:29] Found 0 available updates from Pip
[03/07/24 10:36:34] Found 0 available updates from PowerShell
[03/07/24 10:36:34] Found 2 available updates from Winget
[03/07/24 10:36:34] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[03/07/24 10:36:34] Icon for package SomePythonThings.WingetUIStore.Pre-release was not found, returning default icon
[03/07/24 10:36:37] Resetting administrator rights cache for process id 12220
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.9.1792-preview
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 03/07/24 10:35:04
Process end time:   03/07/24 10:35:04

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Susan\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03/07/24 10:35:06
Process end time:   03/07/24 10:35:09

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/24 10:35:06
Process end time:   03/07/24 10:35:21

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 03/07/24 10:35:07
Process end time:   03/07/24 10:35:07

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/24 10:35:09
Process end time:   03/07/24 10:35:21

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\Susan\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03/07/24 10:36:26
Process end time:   03/07/24 10:36:27

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/24 10:36:27
Process end time:   03/07/24 10:36:34

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Screenshots and videos

Operation Log:
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Starting package update operation for package id=SomePythonThings.WingetUIStore.Pre-release with Manager name=Winget
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe
Process Call Arguments :  update --id SomePythonThings.WingetUIStore.Pre-release --exact --source winget --accept-source-agreements --version "3.1.0-beta1" --silent --disable-interactivity --accept-package-agreements --force --include-unknown
Working Directory      : C:\Users\User
    ║    \ 
    ║ No applicable installer found; see logs for more details.
Process Exit Code      : -1978335216
Process End Time       : 03/07/24 10:36:35
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄

**Comment by marticliment** [comment] 2024-07-03 09:57
duplicate of #2399

**Closed by marticliment** 2024-07-03 09:57 UTC
Labels: bug
