### ISSUE TITLE
[BUG] Unable to update megaSync on win10 x64

### ISSUE THREAD

**Issue by john371911** [marticliment/UniGetUI#2602] opened 2024-08-06 17:46 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.1

### Windows version, edition, and architecture

win10 home edition 22H2 19045.4717

### Describe your issue

Failed to update MegaSync to 5.4.0.0
It showed Unknown of current vision on uniget.
I tried to update MegaSync from the program itself, it said no new update. The current vision is 5.2.1

### UniGetUI Log

```text
[2024/8/6 下午 11:53:43]    __  __      _ ______     __  __  ______
                         / / / /___  (_) ____/__  / /_/ / / /  _/
                        / / / / __ \/ / / __/ _ \/ __/ / / // /
                       / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                       \____/_/ /_/_/\____/\___/\__/\____/___/
                           Welcome to UniGetUI Version 3.1.1
[2024/8/6 下午 11:53:43]
[2024/8/6 下午 11:53:43] Version Code:  3.11
[2024/8/6 下午 11:53:48] Encoding Code Page set to 950
[2024/8/6 下午 11:53:51] Using bundled GSudo at C:\Program Files\UniGetUI\Assets\Utilities\gsudo.exe
[2024/8/6 下午 11:53:55] Loaded language locale: zh_TW
[2024/8/6 下午 11:54:02] Randomly-generated background API auth token for the current session: bwb23zp8oy3x2pn7py5jkubjwgim24u7qot8bypmd4y1gfj4lapuhgv64awp1u4i
[2024/8/6 下午 11:54:07] Api running on http://localhost:7058
[2024/8/6 下午 11:54:11] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Chocolatey
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:13] Command npm was not found on the system
[2024/8/6 下午 11:54:13] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Npm
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:14] Command dotnet.exe was not found on the system
[2024/8/6 下午 11:54:14] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: .NET Tool
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:14] Command pwsh.exe was not found on the system
[2024/8/6 下午 11:54:14] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell7
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:16] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Pip
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: pip
                       █ Executable path: C:\Users\User\AppData\Local\Microsoft\WindowsApps\python.exe
                       █ Call arguments:  -m pip
                       █ Version: 
                       █   
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:20] Command scoop was not found on the system
[2024/8/6 下午 11:54:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Scoop
                       █ Enabled: True
                       █ Found: False
                       █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                       █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:20] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: Winget
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: winget.exe
                       █ Executable path: C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe
                       █ Call arguments: 
                       █ Version: 
                       █   System WinGet CLI Version: v1.8.1911
                       █   Microsoft.WinGet.Client PSModule version: ""
                       █   Using Native WinGet helper (COM Api)
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:29] PowerShell sources took too long to load, using known sources as default
[2024/8/6 下午 11:54:29] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                       █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                       █ Name: PowerShell
                       █ Enabled: True
                       █ Found: True
                       █ Fancy exe name: powershell.exe
                       █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                       █ Call arguments:  -NoProfile -Command
                       █ Version: 
                       █   Name                           Value                                                                                   
                       █   ----                           -----                                                                                   
                       █   PSVersion                      5.1.19041.4717                                                                          
                       █   PSEdition                      Desktop                                                                                 
                       █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                       █   BuildVersion                   10.0.19041.4717                                                                         
                       █   CLRVersion                     4.0.30319.42000                                                                         
                       █   WSManStackVersion              3.0                                                                                     
                       █   PSRemotingProtocolVersion      2.3                                                                                     
                       █   SerializationVersion           1.1.0.1
                       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[2024/8/6 下午 11:54:31] Microsoft.Powershell.Client detection has been forcefully skipped as the module is not required on the current context
[2024/8/6 下午 11:54:31] Dependency WinGet PowerShell Module for manager Winget is present
[2024/8/6 下午 11:54:31] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[2024/8/6 下午 11:54:42] Found 0 available updates from Pip
[2024/8/6 下午 11:54:42] Found 0 installed packages from Pip
[2024/8/6 下午 11:54:42] Found 0 installed packages from PowerShell
[2024/8/6 下午 11:54:42] Found 0 available updates from PowerShell
[2024/8/6 下午 11:54:46] UniGetUI is up to date
[2024/8/6 下午 11:55:19] Error finding sources for manager PowerShell
[2024/8/6 下午 11:55:19] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 381
[2024/8/6 下午 11:55:26] Lang files were updated successfully from GitHub
[2024/8/6 下午 11:55:30] Error finding installed packages on manager Winget
[2024/8/6 下午 11:55:30] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 215
[2024/8/6 下午 11:55:31] Error finding sources for manager PowerShell
[2024/8/6 下午 11:55:31] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetSources() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 381
[2024/8/6 下午 11:55:33] Downloaded new icons and screenshots successfully!
[2024/8/6 下午 11:55:56] Found 1 available updates from Winget
[2024/8/7 上午 12:55:30] UniGetUI is up to date
[2024/8/7 上午 12:55:57] Found 0 available updates from Pip
[2024/8/7 上午 12:56:07] Found 0 available updates from PowerShell
[2024/8/7 上午 12:57:09] Found 3 available updates from Winget
[2024/8/7 上午 12:57:16] Found 0 installed packages from Pip
[2024/8/7 上午 12:57:19] Found 0 installed packages from PowerShell
[2024/8/7 上午 12:57:20] Found 208 installed packages from Winget
[2024/8/7 上午 12:57:24] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/7 上午 12:57:24] Icon for package Microsoft.VCRedist.2015+.x64 was not found, returning default icon
[2024/8/7 上午 12:57:31] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/7 上午 12:57:31] Icon for package Microsoft.VCRedist.2015+.x86 was not found, returning default icon
[2024/8/7 上午 12:57:45] Update
[2024/8/7 上午 12:57:45] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/7 上午 12:57:45] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Mega.MEGASync
[2024/8/7 上午 12:57:45] Icon for package Mega.MEGASync stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Winget\Mega.MEGASync.png
[2024/8/7 上午 12:57:45] Found 0 screenshots for package Id=Mega.MEGASync
[2024/8/7 上午 12:58:05] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/7 上午 12:58:05] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Mega.MEGASync
[2024/8/7 上午 12:58:05] Icon for package Mega.MEGASync stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Winget\Mega.MEGASync.png
[2024/8/7 上午 12:58:53] Loaded details for package Mega.MEGASync on manager Winget
[2024/8/7 上午 01:34:39] Found 0 installed packages from Pip
[2024/8/7 上午 01:34:41] Found 0 installed packages from PowerShell
[2024/8/7 上午 01:35:39] Error finding installed packages on manager Winget
[2024/8/7 上午 01:35:39] System.TimeoutException: The operation has timed out.
                          at UniGetUI.PackageEngine.ManagerClasses.Manager.PackageManager.GetInstalledPackages() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Manager\PackageManager.cs:line 215
[2024/8/7 上午 01:43:27] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[2024/8/7 上午 01:43:27] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=Mega.MEGASync
[2024/8/7 上午 01:43:27] Icon for package Mega.MEGASync stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Winget\Mega.MEGASync.png
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.8.1911
Microsoft.WinGet.Client PSModule version: ""
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/8/6 下午 11:54:20
Process end time:   2024/8/6 下午 11:54:20

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024/8/6 下午 11:54:29
Process end time:   2024/8/6 下午 11:55:04

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024/8/6 下午 11:54:30
Process end time:   2024/8/6 下午 11:55:57

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 2024/8/6 下午 11:54:31
Process end time:   2024/8/6 下午 11:54:38

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024/8/6 下午 11:55:04
Process end time:   2024/8/6 下午 11:55:56

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 2024/8/7 上午 12:55:57
Process end time:   2024/8/7 上午 12:56:22

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 2024/8/7 上午 12:56:22
Process end time:   2024/8/7 上午 12:57:09

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024/8/7 上午 12:57:15
Process end time:   2024/8/7 上午 12:57:20

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 2024/8/7 上午 12:57:39
Process end time:   2024/8/7 上午 12:57:39

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageDetails
Process start time: 2024/8/7 上午 12:57:45
Process end time:   2024/8/7 上午 12:58:53

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is LoadPackageVersions
Process start time: 2024/8/7 上午 12:57:45
Process end time:   2024/8/7 上午 12:57:46

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 2024/8/7 上午 01:34:39
Process end time:   2024/8/7 上午 01:35:48

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment] 2024-08-06 21:03
Hello,

Some packages sometimes fail to be updated since WinGet (one of the package providers) does not properly report their versions. Therefore, this is an issue with WinGet itself (this issue should be reproducable via the winget.exe file), and it can't be fixed within UniGetUI.

In order to circumvent this issue, please right-click the faulting package -> skip this version

**Closed by marticliment** 2024-08-06 21:03 UTC
Labels: bug

**Comment by john371911** [comment] 2024-08-06 21:13
Can it be fixed so I can use uniget to update mega as other programs?
If I report the issue to mega team, is it possible for them to fix it?

**Comment by marticliment** [comment] 2024-08-06 21:39
> Can it be fixed so I can use uniget to update mega as other programs? If I report the issue to mega team, is it possible for them to fix it?

Yes, using the skip this version will prompt UniGetUI to not report this update until a newer version is available, and then the update should work.

This is likely to be an issue with the Mega team publishing and invalid installer/manifest to WinGet, so if you are able to reach them and let them know that would likely fix the issue
