### ISSUE TITLE
[BUG] Software Updates tab sometimes blank even through packages are available to update

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2391] opened 2024-07-02 23:27 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0 beta 2

### Windows version, edition and architecture

Windows 11 Pro

### Describe your issue

Unsure how to trigger this, but I believe at least one time when I pressed refresh when encountering this bug earlier UniGetUI instantly crashed. This time, I can keep pressing refresh, or changing tab, but when I come back to the _Software Updates_ tab, it is still blank despite 2 packages being available to update.

### Steps to reproduce the issue

Unknown. Maybe it's something to do with icons for packages causing this bug as a side effect? Or something specifically related to WinGet? No clue.

### UniGetUI Log

```text
...
[02/07/2024 21:02:28] Found 5 available updates from Scoop
[02/07/2024 21:02:33] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[02/07/2024 21:02:33] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=JetBrains.Toolbox
[02/07/2024 21:02:34] Icon for package JetBrains.Toolbox stored on C:\Users\User\AppData\Local\UniGetUI\CachedMedia\Winget\JetBrains.Toolbox.png
[02/07/2024 21:19:12] Found 0 installed packages from Chocolatey
[02/07/2024 21:19:12] Found 141 installed packages from Pip
[02/07/2024 21:19:13] Found 3 installed packages from PowerShell
[02/07/2024 21:19:13] Found 253 installed packages from Scoop
[02/07/2024 21:19:15] Found 9 installed packages from Npm
[02/07/2024 21:19:22] Found 427 installed packages from Winget
[02/07/2024 23:36:10] Found 0 installed packages from Chocolatey
[02/07/2024 23:36:11] Found 141 installed packages from Pip
[02/07/2024 23:36:13] Found 3 installed packages from PowerShell
[02/07/2024 23:36:13] Found 253 installed packages from Scoop
[02/07/2024 23:36:14] Found 0 available updates from Chocolatey
[02/07/2024 23:36:16] Found 9 installed packages from Npm
[02/07/2024 23:36:17] Found 0 available updates from PowerShell
[02/07/2024 23:36:21] Found 0 available updates from Npm
[02/07/2024 23:36:24] Found 427 installed packages from Winget
[02/07/2024 23:36:25] Found 10 available updates from Winget
[02/07/2024 23:36:33] Found 0 available updates from Pip
[02/07/2024 23:36:35] Found 253 installed packages from Scoop
[02/07/2024 23:36:51] Found 7 available updates from Scoop
[02/07/2024 23:36:53] Non-MSStore WinGet Native Icons have been forcefully disabled on code
[02/07/2024 23:36:53] Icon for package EaseUS.PartitionMaster was not found, returning default icon
[02/07/2024 23:36:55] Loaded icon with URL=UniGetUI.Core.IconEngine.CacheableIcon for package Id=go
[02/07/2024 23:36:56] An error occurred while retrieving the icon for package go
[02/07/2024 23:36:56] System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
                         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
                         at UniGetUI.Core.IconEngine.IconCacheEngine.DownloadIconOrCache(Nullable`1 _icon, String ManagerName, String PackageId) in C:\SomePrograms\WingetUI-Store\src\UniGetUI.Core.IconStore\IconCacheEngine.cs:line 166
                         at UniGetUI.PackageEngine.PackageClasses.Package.GetIconUrl() in C:\SomePrograms\WingetUI-Store\src\UniGetUI.PackageEngine.PackageManagerClasses\Packages\Package.cs:line 199
[02/07/2024 23:36:58] Icon for package zig-dev was not found, returning default icon
[03/07/2024 01:11:42] Found 0 installed packages from Chocolatey
[03/07/2024 01:11:44] Found 3 installed packages from PowerShell
[03/07/2024 01:11:44] Found 141 installed packages from Pip
[03/07/2024 01:11:44] Found 253 installed packages from Scoop
[03/07/2024 01:11:46] Found 0 available updates from Chocolatey
[03/07/2024 01:11:48] Found 9 installed packages from Npm
[03/07/2024 01:11:49] Found 0 available updates from PowerShell
[03/07/2024 01:11:53] Found 0 available updates from Npm
[03/07/2024 01:11:58] Found 427 installed packages from Winget
[03/07/2024 01:11:58] Found 9 available updates from Winget
[03/07/2024 01:12:05] Found 0 available updates from Pip
[03/07/2024 01:12:07] Found 253 installed packages from Scoop
[03/07/2024 01:12:31] Found 5 available updates from Scoop
[03/07/2024 02:11:02] Found 0 available updates from Chocolatey
[03/07/2024 02:11:05] Found 0 available updates from PowerShell
[03/07/2024 02:11:09] Found 0 available updates from Npm
[03/07/2024 02:11:10] Found 9 available updates from Winget
[03/07/2024 02:11:22] Found 253 installed packages from Scoop
[03/07/2024 02:11:24] Found 0 available updates from Pip
[03/07/2024 02:11:38] Found 5 available updates from Scoop
[03/07/2024 02:12:26] Scoop buckets have been already refreshed in the last ten minutes, skipping.
[03/07/2024 02:12:28] Found 0 available updates from Chocolatey
[03/07/2024 02:12:29] Found 253 installed packages from Scoop
[03/07/2024 02:12:31] Found 0 available updates from PowerShell
[03/07/2024 02:12:32] Found 0 available updates from Npm
[03/07/2024 02:12:36] Found 9 available updates from Winget
[03/07/2024 02:12:45] Found 5 available updates from Scoop
[03/07/2024 02:12:46] Found 0 available updates from Pip
[03/07/2024 02:13:50] Scoop buckets have been already refreshed in the last ten minutes, skipping.
[03/07/2024 02:13:51] Found 0 available updates from Chocolatey
[03/07/2024 02:13:53] Found 253 installed packages from Scoop
[03/07/2024 02:13:54] Found 0 available updates from PowerShell
[03/07/2024 02:13:56] Found 0 available updates from Npm
[03/07/2024 02:14:00] Found 9 available updates from Winget
[03/07/2024 02:14:08] Found 5 available updates from Scoop
[03/07/2024 02:14:09] Found 0 available updates from Pip
```

### Package Managers Logs

```text
Manager Winget with version:
Naive WinGet CLI Version: v1.8.1791
Microsoft.WinGet.Client PSModule version: 
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 02/07/2024 21:01:47
Process end time:   02/07/2024 21:01:47

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "D:\Scoop\shims\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 02/07/2024 21:01:50
Process end time:   02/07/2024 21:01:52

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 02/07/2024 21:01:50
Process end time:   02/07/2024 21:02:02

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListSources
Process start time: 02/07/2024 21:01:51
Process end time:   02/07/2024 21:01:52

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 02/07/2024 21:01:52
Process end time:   02/07/2024 21:02:02

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 02/07/2024 21:19:10
Process end time:   02/07/2024 21:19:22

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 02/07/2024 23:36:09
Process end time:   02/07/2024 23:36:24

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "D:\Scoop\shims\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 02/07/2024 23:36:11
Process end time:   02/07/2024 23:36:17

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 02/07/2024 23:36:17
Process end time:   02/07/2024 23:36:25

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListPackages
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/2024 01:11:40
Process end time:   03/07/2024 01:11:58

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "D:\Scoop\shims\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03/07/2024 01:11:42
Process end time:   03/07/2024 01:11:49

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/2024 01:11:49
Process end time:   03/07/2024 01:11:58

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "D:\Scoop\shims\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03/07/2024 02:11:00
Process end time:   03/07/2024 02:11:02

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/2024 02:11:02
Process end time:   03/07/2024 02:11:10

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "D:\Scoop\shims\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03/07/2024 02:12:26
Process end time:   03/07/2024 02:12:27

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/2024 02:12:27
Process end time:   03/07/2024 02:12:36

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "D:\Scoop\shims\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 03/07/2024 02:13:50
Process end time:   03/07/2024 02:13:51

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is ListUpdates
Subprocess executable: "C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe"
Command-line arguments: "-ExecutionPolicy Bypass -NoLogo -NoProfile"
Process start time: 03/07/2024 02:13:51
Process end time:   03/07/2024 02:14:00

-- Process STDIN
 ...

-- Process STDOUT
 ...

-- Process STDERR
  Write-Output : The term '﻿Write-Output' is not recognized as the name of a cmdlet, function, script file, or 
  operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
  again.
  At line:1 char:1
  + ﻿Write-Output (Get-Module -Name Microsoft.WinGet.Client).Version
  + ~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (﻿Write-Output:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException
   

Return code: SUCCESS (0)

——————————————————————————————————————————
```

### Relevant information

Ah. Whatever causes the bug, the temporary solution is to maximise the window (or presumably resize would also work). The 2 packages in the list redrew and now are visible and can be interacted with again.

### Screenshots and videos

Screenshot is immediately after refreshing updates has finished:

![WingetUI_2024-07-03_02-14-19](https://github.com/marticliment/WingetUI/assets/25013746/34309ac7-1508-4425-b0a0-92a5dd2432d1)

**Comment by EckeD** [comment] 2024-07-04 08:21
Had the same happening.
As poster stated: "doing something" with the window fixes the issue. For me, I simply changed the size of the "Sources / Filters" column left of the list view (using the small handle between both frames) - that also refreshed the view and updates were shown again.

**Comment by ChaoticHolon** [comment] 2024-07-07 09:44
This is happening to me as well, quite annoying. Started after updating to 3.1.0.

**Comment by marticliment** [comment] 2024-07-07 10:44
Hello,

To all users facing issues with version 3.1.0, please try the new 3.1.1 beta, which aims to fix this issues.

UniGetUI 3.1.1-beta0 release: https://github.com/marticliment/UniGetUI/releases/tag/3.1.1-beta0
Direct installer URL: https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe

Excuse me for the inconveniences.

**Comment by marticliment** [comment] 2024-07-13 16:29
I think the cause of this issue is the same as https://github.com/marticliment/UniGetUI/issues/2464

**Comment by eidylon** [comment] 2024-07-23 13:19
Just adding my voice as someone also getting this issue. v.3.1.0. 

At least now I know from this thread resizing the window makes them show.

**Comment by marticliment** [comment] 2024-07-23 14:21
I suspect loading icons from the hard drive (versions prior to b3), which takes a long time, somehow broke the renderer. I am going to close this then.

**Comment by Lockszmith-GH** [comment] 2024-07-25 15:39
![WingetUI_Bug animated](https://github.com/user-attachments/assets/542f6a9d-e73f-470a-8e83-a520418641f2)
Just to show everyone how this actually looks like.

**Comment by Lockszmith-GH** [comment] 2024-08-07 13:50
Had a totaly new experience today. Resize didn't bring it back like in the animated gif I posted earlier. Instead the only thing that actually worked was unchecking my source and checking it again. I'll try and capture it the next time it happens.

**Comment by only-su** [comment] 2024-08-15 12:41
> Had a totaly new experience today. Resize didn't bring it back like in the animated gif I posted earlier. Instead the only thing that actually worked was unchecking my source and checking it again. I'll try and capture it the next time it happens.
> 
> I'm on 3.1.1

This seem related to #2635

**Comment by marticliment** [comment] 2024-08-16 17:06
I wil test it out, thanks!

**Comment by Lockszmith-GH** [comment] 2024-08-21 16:54
I've recorded clearing the checkboxes, which didn't make a difference.

However, I can add - that after this recording, when I hit Clear Selection, the application crashed (will not file a bug if this repeats)

![UniGetUI_GyHaZRLt1f](https://github.com/user-attachments/assets/6a2abee3-bf04-4ae7-be45-9d625a638c70)

**Closed** 2024-08-30 16:30 UTC
Labels: bug, needs-further-study

**Comment by Lockszmith-GH** [comment] 2024-08-31 17:32
In the MR you stated
> This does NOT fix the issue where the page doesn't render.

I thought this was the 'does not render' issue - can you please point me at the still open bug?

**Comment by marticliment** [comment] 2024-08-31 18:21
Sorry, the initial idea was not to fix it, but I finally ended up fixing it
