### ISSUE TITLE
[BUG] Powershell parameter cannot be found that matches parameter name 'Scope'

### ISSUE THREAD

**Issue by aferrazlr** [marticliment/UniGetUI#2914] opened 2024-10-30 15:56 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.3

### Windows version, edition, and architecture

Windows 11 Pro Version	23H2 1000.22700.1047.0

### Describe your issue

Uniget uses the following command to update Winget client from version 1.9.2411 to 1.9.25180:

`powershell.exe Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser`

Then it returns the following error message:

> Starting package update operation for package id=Microsoft.WinGet.Client with Manager name=PowerShell
> Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
> Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
> Process Call Arguments :  -NoProfile -Command Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
> Working Directory      : C:\Users\A
> Process Start Time     : 2024-10-30 15:23:30
> Update-Module : A parameter cannot be found that matches parameter name 'Scope'.
> At line:1 char:68
> + ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
> +                                                            ~~~~~~
> + CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
> + FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
> Process Exit Code      : 1
> Process End Time       : 2024-10-30 15:23:31
> 

### Steps to reproduce the issue

update Winget client from version 1.9.2411 to 1.9.25180

### UniGetUI Log

```text
Starting package update operation for package id=Microsoft.WinGet.Client with Manager name=PowerShell
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -Command Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
Working Directory      : C:\Users\A
Process Start Time     : 2024-10-30 15:22:33
Update-Module : A parameter cannot be found that matches parameter name 'Scope'.
At line:1 char:68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
Process Exit Code      : 1
Process End Time       : 2024-10-30 15:22:36
```

### Package Managers Logs

```text
Starting package update operation for package id=Microsoft.WinGet.Client with Manager name=PowerShell
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -Command Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
Working Directory      : C:\Users\A
Process Start Time     : 2024-10-30 15:22:33
Update-Module : A parameter cannot be found that matches parameter name 'Scope'.
At line:1 char:68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
Process Exit Code      : 1
Process End Time       : 2024-10-30 15:22:36
```

**Comment by marticliment** [comment] 2024-10-30 18:52
Duplicate of #2814

**Closed by marticliment** 2024-10-30 18:52 UTC
Labels: bug
