### ISSUE TITLE
[BUG] Error on Install after selecting language

### ISSUE THREAD

**Issue by erab76** [marticliment/UniGetUI#2494] opened 2024-07-14 10:08 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11 Home 23H2 Build 22631.3880

### Describe your issue

When installing UniGetUi version 3.0.1, after selecting the language, the installation crashes with the following error message::

![Screenshot 2024-07-14 120221](https://github.com/user-attachments/assets/dc86e54f-eecd-4b3e-a68f-c56ab3784cec)

Disabling the antivirus doesn't solve the problem

### UniGetUI Log

```text
No UniGetUi Logs available
```

### Package Managers Logs

```text
No Package Manager Logs are available
```

**Comment by marticliment** [comment] 2024-07-14 10:33
This looks like a windows error. Please try running a health check: https://www.windowscentral.com/how-use-dism-command-line-utility-repair-windows-10-image

**Comment by erab76** [comment] 2024-07-14 12:16
Checkhed with ot DISM and SFC,  no errors found.
The problem is only on UniGetUI 3.1.0, the WinGetUI 3.0.2 installation works fine.

**Comment by marticliment** [comment] 2024-07-14 16:38
I will investigate, but I am afraid this is not directly caused by UniGetUI

**Comment by erab76** [comment] 2024-07-15 11:39
I think the problem is related to the installer and not the app. Could it be it is trying to uninstall the previous version even if not present?

**Comment by marticliment** [comment] 2024-07-15 13:07
No, the installer does not call the uninstaller, it just overwrites the installation

**Comment by erab76** [comment] 2024-07-15 21:54
I tried launching the installer from powershell with the option /LOG

This is the result:

2024-07-15 23:21:51.016   Log opened. (Time zone: UTC+02:00)
2024-07-15 23:21:51.017   Setup version: Inno Setup version 6.2.2
2024-07-15 23:21:51.017   Original Setup EXE: C:\Users\bare7\Downloads\UniGetUI.Installer.exe
2024-07-15 23:21:51.017   Setup command line: /SL5="$200550,52105540,1228800,C:\Users\bare7\Downloads\UniGetUI.Installer.exe" /LOG=C:\Users\bare7\Downloads\log.txt
2024-07-15 23:21:51.017   Windows version: 10.0.22631  (NT platform: Yes)
2024-07-15 23:21:51.018   64-bit Windows: Yes
2024-07-15 23:21:51.018   Processor architecture: x64
2024-07-15 23:21:51.018   User privileges: Administrative
2024-07-15 23:21:51.028   Administrative install mode: Yes
2024-07-15 23:21:51.028   Install mode root key: HKEY_LOCAL_MACHINE
2024-07-15 23:21:51.029   64-bit install mode: No
2024-07-15 23:21:53.105   Created temporary directory: C:\Users\bare7\AppData\Local\Temp\is-SJCUF.tmp
2024-07-15 23:21:53.106   -- DLL function import --
2024-07-15 23:21:53.106   Function name: ExitProcess
2024-07-15 23:21:53.106   DLL name: kernel32.dll
2024-07-15 23:21:53.106   Dest DLL name: kernel32.dll
2024-07-15 23:21:53.106   Importing the DLL function.
2024-07-15 23:21:53.106   Successfully imported the DLL function. Delay loaded? No
2024-07-15 23:21:53.107   InitializeSetup raised an exception (fatal).
2024-07-15 23:21:53.107   Exception message:
2024-07-15 23:21:53.107   Message box (OK):
                          Runtime error (at 40:328):
                          
                          This action is only valid for products that are currently installed.
2024-07-15 23:21:54.267   User chose OK.
2024-07-15 23:21:54.268   Deinitializing Setup.
2024-07-15 23:21:54.269   Log closed.

Seems a problem related to the dependencies.

Both Webiew2 and VisualC++ 2015-2022 are installed.
I will try investigating the IsMsiProductInstalled function of the installer.

**Comment by erab76** [comment] 2024-07-16 09:15
Compiling the WingetUI.iss with Inno Setup 6 the error appears in CodeDependencies.iss when checking for Visual C

procedure Dependency_AddVC2015To2022;
begin
  // https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
  **if not IsMsiProductInstalled(Dependency_String('{36F68A90-239C-34DF-B58C-64B30153CE35}', '{36F68A90-239C-34DF-B58C-64B30153CE35}'), PackVersionComponents(14, 30, 30704, 0)) then begin**
    Dependency_Add('vcredist2022' + Dependency_ArchSuffix + '.exe',
      '/passive /norestart',
      'Visual C++ 2015-2022 Redistributable (x64)' + Dependency_ArchTitle,
      Dependency_String('https://aka.ms/vs/17/release/vc_redist.x64.exe', 'https://aka.ms/vs/17/release/vc_redist.x64.exe'),
      '', False, False);
  end;
end;

**Comment by marticliment** [comment] 2024-07-16 12:32
Will add an option to skip installation of vcredist

**Comment by hfm158** [comment] 2024-07-28 17:17
This is a duplicate of #2460

**Comment by marticliment** [comment] 2024-07-28 19:16
Closing as duplicate

**Closed by marticliment** 2024-07-28 19:16 UTC
Labels: bug, ready-to-go

**Comment by CodeAru** [comment] 2024-08-24 18:29
Hello I have the same issue at my end. But my OS is Windows 10.

Is there a dependency I am missing?
