### ISSUE TITLE
[IMPROVEMENT] Opt-in to update Powershell modules with scope AllUsers

### ISSUE THREAD

**Issue by TDarkShadow** [marticliment/UniGetUI#2967] opened 2024-11-13 12:34 UTC
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

By default, updating modules in Powershell 5 and 7, will update them under the CurrentUser scope.
This is a problem when the user / machine uses OneDrive, since OneDrive syncs $HOME\Documents, and the additional Powershell modules takes storage space and causes conflicts on other synced machines.
By installing them with the AllUsers scope, the modules will be installed to $env:ProgramFiles\PowerShell\Modules, which is outside known folders of OneDrive.

### Describe how this improvement could help users

Less OneDrive storage space use, less to none Powershell modules conflicts on synced machines.

**Comment by marticliment** [comment] 2024-11-13 20:49
This is a duplicate of https://github.com/marticliment/UniGetUI/issues/2059

**Closed by marticliment** 2024-11-13 20:49 UTC
Labels: enhancement
