### ISSUE TITLE
[BUG] (Enter your description here)

### ISSUE THREAD

**Issue by ten24bytes** [marticliment/UniGetUI#2479] opened 2024-07-12 06:44 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition, and architecture

Windows 11 Pro

### Describe your issue

The installer still has old strings which say WinGet

### Steps to reproduce the issue

Run the latest installer
You can see the references to WinGet during the installation steps, e.g. "Ensuring WinGet is installed properly".
![WinGet Installer](https://github.com/user-attachments/assets/90acbae1-bad1-41e5-89f6-55a4122782df)

### UniGetUI Log

```text
This is related to the installer so not applicable
```

### Package Managers Logs

```text
This is related to the installer so not applicable
```

**Comment by hboyd2003** [comment] 2024-07-12 18:48
WinGet and WinGetUI/UniGetUI is not the same thing. UniGetUI was originally named WinGetUI as it was a GUI for the package manager WinGet. WinGetUI added support for other packages managers and the name no longer fit, however, it still supports the WinGet package manager.

**Comment by marticliment** [comment] 2024-07-13 16:41
duplicate of #2473

**Closed** 2024-07-13 16:41 UTC
Labels: bug

**Comment by ten24bytes** [comment] 2024-07-14 12:50
> WinGet and WinGetUI/UniGetUI is not the same thing. UniGetUI was originally named WinGetUI as it was a GUI for the package manager [WinGet](https://en.wikipedia.org/wiki/Windows_Package_Manager). WinGetUI added support for other packages managers and the name no longer fit, however, it still supports the WinGet package manager.

sorry, my bad!
