### ISSUE TITLE
[ENHANCEMENT] selective autoupdate for apps (whitelisting)

### ISSUE THREAD

**Issue by Saibaschbeis** [marticliment/UniGetUI#2616] opened 2024-08-09 08:53 UTC
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Currently, WinGetUI allows to enable autoupdate, to automatically install any updates found.
However, this relies on updates to actually work as intended - silently, without any interaction etc.
Unfortunately this is not always the case. Some applications do not update properly when running automatically.
Thus I usually disable autoupdate, and also am hesitant enabling it for anyone not tech-savvy enough in case something breaks.

Therefore, I would propose an additional enhancement by allowing "selective autoupdate".
How this would work is: autoupdate is disabled by default, however if I want a specific app I know to cause no issues during update to autoupdate, I mark it as such and WinGetUI then adds it to a whitelist. Any app in that whitelist is then autoupdated.

Should be quite easy to implement - just first check if an app is in that whitelist, and if not stop the autoupdate process.

### Describe how this improvement could help users

It would be possible to auto-update at least part of the apps, thus the actual manual work is decreased.
Also makes it more feasible to enable autoupdates on computers used by non-techies, who don't know what they are doing (as in WinGetUI was installed by the admin / son / grandson etc., helping out family ;)), if they have some apps that are not updating correctly with WinGetUI.

**Comment by marticliment** [comment] 2024-08-09 13:49
Duplicate of #1383

**Closed** 2024-08-09 13:49 UTC
Labels: enhancement

**Comment by Saibaschbeis** [comment] 2024-08-16 07:48
sorry, apparently my search skills in Github suck...
