### ISSUE TITLE
Software updates in Unigetui fail with  unsigned signature error

### ISSUE THREAD

**Issue by bnw42** [marticliment/UniGetUI#3080] opened 2024-12-17 22:12 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.4

### Windows version, edition, and architecture

Windows 10 Pro 10.0.19045

### Describe your issue

UnigetUI just updated to 3.1.4 after which it flagged two software updates (which UnigetUI has updated before) but both failed with the error:

Error: Parent process signature is not SignedAndTrusted: Unsigned
Warning: W_UNRECOGNIZED_PARENT_ASSEMBLY_SIGNATURE
Error: The Elevator was not called from a trusted process
Process Exit Code      : -1

The previous version was working fine.

### Steps to reproduce the issue

Go to the 'software updates' option in the LHS menu, then attempt to install any update, either as admin or not.

### UniGetUI Log

```text
[18/12/2024 8:52:18 AM]    __  __      _ ______     __  __  ______
                          / / / /___  (_) ____/__  / /_/ / / /  _/
                         / / / / __ \/ / / __/ _ \/ __/ / / // /
                        / /_/ / / / / / /_/ /  __/ /_/ /_/ // /
                        \____/_/ /_/_/\____/\___/\__/\____/___/
                            Welcome to UniGetUI Version 3.1.4
[18/12/2024 8:52:18 AM]
[18/12/2024 8:52:18 AM] Build 73
[18/12/2024 8:52:18 AM] Encoding Code Page set to 850
[18/12/2024 8:52:18 AM] Using built-in UniGetUI Elevator
[18/12/2024 8:52:18 AM] Loaded language locale: en
[18/12/2024 8:52:19 AM] Randomly-generated background API auth token for the current session: ubj306fa9ygvp26k355ijsc7micvs1844ituo25bghb14gy278toqli9nis6xvel
[18/12/2024 8:52:19 AM] Api running on http://localhost:7058
[18/12/2024 8:52:19 AM] Lang files were updated successfully from GitHub
[18/12/2024 8:52:19 AM] Command npm was not found on the system
[18/12/2024 8:52:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Npm
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:19 AM] Command vcpkg was not found on the system
[18/12/2024 8:52:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: vcpkg
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:19 AM] Downloaded new icons and screenshots successfully!
[18/12/2024 8:52:19 AM] Command cargo was not found on the system
[18/12/2024 8:52:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Cargo
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: .NET Tool
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Pip
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:19 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Winget
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: winget.exe
                        █ Executable path: C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe
                        █ Call arguments: 
                        █ Version: 
                        █   System WinGet CLI Version: v1.9.25200
                        █   Using Native WinGet helper (COM Api)
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:20 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Chocolatey
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: choco.exe
                        █ Executable path: C:\Users\User\AppData\Local\UniGetUI\Chocolatey\choco.exe
                        █ Call arguments: 
                        █ Version: 
                        █   2.2.2
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:20 AM] Command scoop was not found on the system
[18/12/2024 8:52:20 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: Scoop
                        █ Enabled: True
                        █ Found: False
                        █ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
                        █ INSTALLED OR IT HAS BEEN MISCONFIGURED 
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:20 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell7
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: pwsh.exe
                        █ Executable path: C:\Program Files\PowerShell\7\pwsh.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   PowerShell 7.4.6
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:22 AM] ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                        █▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
                        █ Name: PowerShell
                        █ Enabled: True
                        █ Found: True
                        █ Fancy exe name: powershell.exe
                        █ Executable path: C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
                        █ Call arguments:  -NoProfile -Command
                        █ Version: 
                        █   Name                           Value                                                                                   
                        █   ----                           -----                                                                                   
                        █   PSVersion                      5.1.19041.5247                                                                          
                        █   PSEdition                      Desktop                                                                                 
                        █   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
                        █   BuildVersion                   10.0.19041.5247                                                                         
                        █   CLRVersion                     4.0.30319.42000                                                                         
                        █   WSManStackVersion              3.0                                                                                     
                        █   PSRemotingProtocolVersion      2.3                                                                                     
                        █   SerializationVersion           1.1.0.1
                        ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
[18/12/2024 8:52:22 AM] LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
[18/12/2024 8:52:23 AM] Found 0 installed packages from Chocolatey
[18/12/2024 8:52:23 AM] Found 0 installed packages from PowerShell7
[18/12/2024 8:52:23 AM] Found 0 available updates from Chocolatey
[18/12/2024 8:52:23 AM] Found 0 available updates from PowerShell7
[18/12/2024 8:52:24 AM] Found 9 available updates from Winget
[18/12/2024 8:52:24 AM] Found 407 installed packages from Winget
[18/12/2024 8:52:25 AM] Found 1 installed packages from PowerShell
[18/12/2024 8:52:25 AM] Backup saved to C:\Users\User\Documents\UniGetUI\HAL9000B installed packages 2024-12-18 08-52-25.ubundle
[18/12/2024 8:52:26 AM] Found 0 available updates from PowerShell
[18/12/2024 8:52:33 AM] Icon download attempt at https://community.chocolatey.org/content/packageimages/boinc.7.20.2.png failed with code NotFound
[18/12/2024 8:52:45 AM] Icon download attempt at https://community.chocolatey.org/content/packageimages/eraser.6.2.0.2993.png failed with code NotFound
[18/12/2024 8:55:35 AM] Loaded operation parameters for package id=Foxit.FoxitReader.Inno on manager Winget and operation Update: update --id "Foxit.FoxitReader.Inno" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[18/12/2024 8:55:40 AM] Loaded operation parameters for package id=Foxit.FoxitReader.Inno on manager Winget and operation Update: update --id "Foxit.FoxitReader.Inno" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[18/12/2024 8:55:45 AM] Loaded operation parameters for package id=Foxit.FoxitReader.Inno on manager Winget and operation Update: update --id "Foxit.FoxitReader.Inno" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[18/12/2024 8:56:01 AM] Loaded operation parameters for package id=Daum.PotPlayer on manager Winget and operation Update: update --id "Daum.PotPlayer" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[18/12/2024 8:56:10 AM] Loaded operation parameters for package id=Daum.PotPlayer on manager Winget and operation Update: update --id "Daum.PotPlayer" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
[18/12/2024 9:05:12 AM] Loaded operation parameters for package id=Foxit.FoxitReader.Inno on manager Winget and operation Update: update --id "Foxit.FoxitReader.Inno" --exact --source winget --accept-source-agreements --disable-interactivity --silent --include-unknown --accept-package-agreements --force
```

### Package Managers Logs

```text
Manager WinGet with version:
System WinGet CLI Version: v1.9.25200
Using Native WinGet helper (COM Api)

——————————————————————————————————————————


Logged native task on manager Winget. Task type is ListSources
Process start time: 18/12/2024 8:52:19 AM
Process end time:   18/12/2024 8:52:19 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged subprocess-based task on manager Winget. Task type is RefreshIndexes
Subprocess executable: "C:\Users\User\AppData\Local\Microsoft\WindowsApps\winget.exe"
Command-line arguments: " source update --disable-interactivity"
Process start time: 18/12/2024 8:52:22 AM
Process end time:   18/12/2024 8:52:23 AM

-- Process STDOUT
 ...

Return code: SUCCESS (0)

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListInstalledPackages
Process start time: 18/12/2024 8:52:22 AM
Process end time:   18/12/2024 8:52:24 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is OtherTask
Process start time: 18/12/2024 8:52:22 AM
Process end time:   18/12/2024 8:52:23 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————

Logged native task on manager Winget. Task type is ListUpdates
Process start time: 18/12/2024 8:52:23 AM
Process end time:   18/12/2024 8:52:24 AM

-- Task information
 ...

The task reported success

——————————————————————————————————————————
```

**Comment by marticliment** [comment] 2024-12-18 07:10
> notice the change log says 3.1.4 uses UniGetUI Elevator instead of GSudo. WOuld the fix be as simple as installing UniGetUI Elevator? Although I would have thought the update to 3.1.4 would have included that as part of the update if it was now required?? BUt there are no releases of UniGetUI Elevator??

No, UniGetUI Elevator is installed, the crash is happening due to UniGetUI Elevator not being able to verify the UniGetUI.exe executable authenticity.

You can upgrade to UniGetUI 3.1.4 and then, under Experimental Settings, disable the "Enable the new, UniGetUI-branded UAC Elevator".

Could you please go to `C:\Program Files\UniGetUI` right-click `UniGetUI.exe` -> Properties -> Digital signatures -> Click on Properties and attach a screenshot here with the contents of the shown window?

**Comment by marticliment** [comment] 2024-12-18 09:02
Do you have the latest patches installed on your windows machine?
Is your machine managed by an entreprise/organization?

**Comment by marticliment** [comment] 2024-12-18 19:01
Yes, I meant windows patches.
Please try manually installing this patch: 
https://support.microsoft.com/en-us/topic/kb5022661-windows-support-for-the-trusted-signing-formerly-azure-code-signing-program-4b505a31-fa1e-4ea6-85dd-6630229e8ef4

**Comment by marticliment** [comment] 2024-12-18 23:04
This is weird then, I don't understand why your Windows machine shouldn't trust the signature... 
The Elevator is quitting because Windows is reporting the UniGetUI.exe cert as invalid.

**Comment by marticliment** [comment] 2024-12-19 07:54
if you update them now, does the signature show as validated?

**Comment by marticliment** [comment] 2024-12-19 22:10
I have contacted the Trusted Signing team, to see if they can help figuring out what is going on.
For the time being, please stick with disabling UniGetUI Elevator and resorting to GSudo

**Comment by marticliment** [comment] 2024-12-19 23:18
> I also have Unigetui on a laptop. Just booted that up & it upgraded to v3.1.4 and installed a software update with no issue. When unigetui updated I got a message about needing to install .net outdated, but attempting that I got an error. I then tried manually and got this error:
> 
> >

You need a newer version of the .NET SDK, such as 6.0 or 8.0

**Comment by marticliment** [comment] 2024-12-19 23:19
> Thanks. I'll be interested in what the TS team has to say, tho' I suspect it is probably related to whatever issues is preventing winupdate from working properly. It detects that updates are available, but errors out when trying to search or download updates. I keep an eye on the MS catalogue and manually dl & install updates. Certificates are updated via winupdate, so I have to update them manually as well. I have written a batch file to do that which runs silently on startup, cleans up after itself and appends update details to a log.

You may have probably already done that, but have you tried running `dism` and `sfc`? I have had luck with this commands in the past when having issues with Windows.

**Comment by marticliment** [comment] 2024-12-20 09:44
Sorry, you need the SEK version (preferably 6 or 8)

**Comment by marticliment** [comment] 2024-12-20 09:57
On the MS Support article about TS Certs says that you need the Microsoft Identity Verification Root Certificate Authority 2020 to be installed, have you tried to install it manually? It says it can be downloaded from here: https://www.microsoft.com/pkiops/docs/repository.htm

**Comment by marticliment** [comment] 2024-12-20 10:19
> I've installed the verification certificate on the desktop & turned back on the unigetui elevator. There are no updates pending so is there any other way of checking to see if installing that certificate has fixed the problem? Other than waiting until an update comes in?

If the UniGetUI digital signature shows as recognized, UniGetUI elevator should work fine.




> I've installed SDK 8 on the laptop. Since I'd already told it not to show that error message & it seems to have been working ok despite the error, is there any way of telling if that fixes that problem?

run on a command prompt `dotnet tool install dotnet-tools-outdated`

**Comment by marticliment** [comment] 2024-12-20 10:56
> On the laptop "dotnet tool install dotnet-tools-outdated" returns "cannot find a manifest file"

My bad. The command should be `dotnet tool install dotnet-tools-outdated -g`



> Going back up the certificate path from your certificate, all of the certificates in the chain are "verified" apart from the top one, "Microsoft Identity Verification Root Certificate Authority 2020", which has the message: "This CA Root certificate is not trusted because it is not in the Trusted Root Certification Authorities store." On a hunch I tried reinstalling the certificate again, this time manually picking the location, viz "Trusted Root Certification Authorities", whereup I got a warning (didn't when I did the automatic install) and an advisory to check the hash. The hash matched, so I went ahead. Then back to unigetui.exe to check the certificates and voila, the whole chain is trusted, including "Microsoft Identity Verification Root Certificate Authority 2020". Evidently the autoinstall is putting the certificate into the wrong certificate store! It hasn't fixed the winupdate issue, a shame, but that was wishful thinking. Anyways, fingers crossed the unigetui elevator will now work properly on the desktop ... once a software update arrives I'll be able to confirm. Assuming it does, thanks heaps for your help.

If Windows reports the cert as verified, it will (or at least should) work. the Elevator checks the caller executable to have my digital signature.

**Comment by marticliment** [comment] 2024-12-20 12:07
> Off topic but the certificates page you gave me the link for had a whole lot of other certificates listed as well. Any idea where I can get a list of what certificate stores each one should be in given the certificate install wizard is evidently not too smart? If I've got one certificate in the wrong store, there's a good chance I've got more that're misplaced. I tried a web search, but it didn't show up anything relevant and the page you gave me the link for is sparse on details.

To be honest, I only know the basic workings of code signing, so I can't help with that.

I am going to close this issue as resolved, as it wasn't caused by UniGetUI itself, but rather by Windows.

**Closed** 2024-12-20 12:07 UTC
Labels: bug, waiting-for-something

**Comment by marticliment** [comment] 2025-03-10 13:23
Please remember that Windows Server 2019 is not officially supported
