### ISSUE TITLE
[CRASH] Microsoft.WinGet.CLient update failed

### ISSUE THREAD

**Issue by blmuzzy** [marticliment/UniGetUI#2921] opened 2024-11-02 19:30 UTC
### Please confirm these before moving forward.

- [X] I have tried deleting a folder named `UniGetUI` under `%UserProfile%\AppData\Local\UniGetUI`.
- [X] I have tried reinstalling UniGetUI.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

I ran "Update selected packages" in unigetUI on windows 10 pro 64-bit.  I deleted appdata folders (uniget & winget).  I deleted uniget and reinstalled with the current ver from github.  other packages update as expected.  I recall updating win/uniget from within win/uniget previously.  

### Logs (if possible)

```text
-
-
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.



▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
                           
Update-Module : A parameter cannot be found that matches parameter name 'Scope'.
At line:1 char:68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
```

**Comment by marticliment** [comment] 2024-11-02 21:59
Duplicate of #2814

**Closed by marticliment** 2024-11-02 21:59 UTC
Labels: bug, important
