### ISSUE TITLE
[IMPROVEMENT] faster mousover on column

### ISSUE THREAD

**Issue by leminsc8er** [marticliment/UniGetUI#3132] opened 2024-12-25 23:12 UTC
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

Like titel.
Optional show instantly by mousover.
See faster installpath for smal Colum.

### Describe how this improvement could help users

faster Experience

**Comment by marticliment** [comment] 2024-12-26 00:43
Duplicate of https://github.com/marticliment/UniGetUI/issues/2988

**Closed by marticliment** 2024-12-26 00:43 UTC
Labels: enhancement
