### ISSUE TITLE
[BUG] Self update error [Scoop WingetUI]

### ISSUE THREAD

**Issue by essenciary** [marticliment/UniGetUI#2149] opened 2024-04-19 11:58 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose))

### Describe your issue

I keep getting the in-app notification that WingetUI 3.02 is ready to be installed. I have updated from within the notification multiple times, the notification keeps coming back. I've also downloaded the latest release from Github and installed manually. The notification keeps coming back. 

Probably related, WingetUI first crashes after an update. I start the app, then the app exists without showing a UI. Restarting successfully runs the app, with the update notification. So maybe the update fails (crashes the app) and some sort of rollback kicks in? 

![image](https://github.com/marticliment/WingetUI/assets/11292378/6b101605-884d-4e29-8ac2-44d2eade8e2e)

### Steps to reproduce the issue

Open the app, you'll see the update notification. Use "Update now" to update and restart the app. The notification will show up again. 

### WingetUI Log

```text
The log is bottom left, in "More" (not top right as it says here). 


Welcome to WingetUI Version 3.0.1
               Version Code 3.01
C:\Users\adria\AppData\Local\WingetUI\CachedLangFiles\lang_en.json
Loaded language locale: en
Api auth token: *****
Starting update check
Api running on http://localhost:7058
Lang files were updated successfully
Updates found, downloading installer...
Current version: 3.01
Latest version : 3.02
Downloaded icons and screenshots successfully!
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Npm
█ Enabled: True
█ Found: False
█ THE MANAGER WAS NOT FOUND. PERHAPS IT IS NOT 
█ INSTALLED OR IT HAS BEEN MISCONFIGURED 
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: .NET Tool
█ Enabled: True
█ Found: True
█ Fancye exe name: dotnet tool
█ Executable path: C:\Program Files\dotnet\dotnet.exe
█ Call arguments: tool
█ Version: 
█   8.0.204
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Pip
█ Enabled: True
█ Found: True
█ Fancye exe name: pip
█ Executable path: C:\Users\adria\AppData\Local\Microsoft\WindowsApps\python.exe
█ Call arguments:  -m pip
█ Version: 
█   
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Starting scoop cleanup...
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Chocolatey
█ Enabled: True
█ Found: True
█ Fancye exe name: choco.exe
█ Executable path: C:\Users\adria\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█ Call arguments: 
█ Version: 
█   2.2.2
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Winget
█ Enabled: True
█ Found: True
█ Fancye exe name: winget.exe
█ Executable path: C:\Users\adria\scoop\apps\wingetui\current\PackageEngine\Managers\winget-cli_x64\winget.exe
█ Call arguments: 
█ Version: 
█   v1.7.10582
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: Scoop
█ Enabled: True
█ Found: True
█ Fancye exe name: scoop
█ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop
█ Version: 
█   Current Scoop version:
█   v0.3.1 - Released at 2022-11-15
█   
█   'extras' bucket:
█   0070306f4 stirling-pdf: Update to version 0.22.7
█   
█   'main' bucket:
█   c4ec1a34a bun(-baseline): Add version 1.1.0 (#5672)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀▀▀▀▀ MANAGER LOADED ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
█ Name: PowerShell
█ Enabled: True
█ Found: True
█ Fancye exe name: powershell.exe
█ Executable path: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█ Call arguments:  -NoProfile -Command
█ Version: 
█   Name                           Value                                                                                   
█   ----                           -----                                                                                   
█   PSVersion                      5.1.22621.2506                                                                          
█   PSEdition                      Desktop                                                                                 
█   PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
█   BuildVersion                   10.0.22621.2506                                                                         
█   CLRVersion                     4.0.30319.42000                                                                         
█   WSManStackVersion              3.0                                                                                     
█   PSRemotingProtocolVersion      2.3                                                                                     
█   SerializationVersion           1.1.0.1
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
LoadComponentsAsync finished executing. All managers loaded. Proceeding to interface.
Error finding updates on manager .NET Tool: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\dotnet-tools-outdated.exe' with working directory 'C:\Users\adria\scoop\apps\wingetui\current'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Dotnet.GetAvailableUpdates_UnSafe() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Dotnet.cs:line 83
   at ModernWindow.PackageEngine.Classes.PackageManager.GetAvailableUpdates() in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 164
Waiting for mainWindow to be hidden
Starting check for updates wait interval with waitTime=86400
Start backup
Finished loading serializable objects. Serializing with format JSON
Finished serializing
Backup saved to C:\Users\adria\Documents\WingetUI\Z13 installed packages 2024-04-19 13-36-42.json
Error finding packages on manager Scoop with query mail: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\scoop-search.exe' with working directory 'C:\Users\adria\scoop\apps\wingetui\current'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Scoop.FindPackages_UnSafe(String query) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Scoop.cs:line 40
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
Error finding packages on manager Pip with query mail: 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ThisExe\WasNotFound\InPath\parse_pip_search' with working directory 'C:\Users\adria\scoop\apps\wingetui\current'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at ModernWindow.PackageEngine.Managers.Pip.FindPackages_UnSafe(String query) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Managers\Pip.cs:line 39
   at ModernWindow.PackageEngine.Classes.PackageManager.FindPackages(String query) in Y:\WingetUI-Store\src\wingetui\PackageEngine\Classes\Manager.cs:line 135
```
```


### Package Managers Logs

```text
(Agan, it's bottom left)


▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:33 PM] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[19-Apr-24 1:36:33 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:34 PM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\scoop\apps\wingetui\current\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[19-Apr-24 1:36:34 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:34 PM] Scoop ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list
Name   Source                                   Updated              Manifests
----   ------                                   -------              ---------
extras https://github.com/ScoopInstaller/Extras 02-Apr-24 2:35:03 AM      1999
main   https://github.com/ScoopInstaller/Main   02-Apr-24 3:28:46 AM      1312
[19-Apr-24 1:36:34 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:35 PM] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[19-Apr-24 1:36:35 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:35 PM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\scoop\apps\wingetui\current\PackageEngine\Managers\winget-cli_x64\winget.exe
█  Arguments:  source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
[19-Apr-24 1:36:35 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:36 PM] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\AppData\Local\Microsoft\WindowsApps\python.exe
█  Arguments:  -m pip list --outdated
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
[19-Apr-24 1:36:36 PM] Exit Code: 9009
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:36 PM] Pip ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\AppData\Local\Microsoft\WindowsApps\python.exe
█  Arguments:  -m pip list
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
[19-Apr-24 1:36:36 PM] Exit Code: 9009
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:37 PM] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  source list
Chocolatey v2.2.2
chocolatey - https://community.chocolatey.org/api/v2/ | Priority 0|Bypass Proxy - False|Self-Service - False|Admin Only - False.
[19-Apr-24 1:36:37 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:37 PM] Scoop ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop bucket list
Name   Source                                   Updated              Manifests
----   ------                                   -------              ---------
extras https://github.com/ScoopInstaller/Extras 02-Apr-24 2:35:03 AM      1999
main   https://github.com/ScoopInstaller/Main   02-Apr-24 3:28:46 AM      1312
[19-Apr-24 1:36:37 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:37 PM] .NET Tool ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Program Files\dotnet\dotnet.exe
█  Arguments: tool list --global
Package Id      Version      Commands
-------------------------------------
[19-Apr-24 1:36:37 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:37 PM] Scoop ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop list
Installed apps:
Name     Version Source Updated             Info
----     ------- ------ -------             ----
7zip     23.01   main   2024-03-27 22:30:54     
git      2.44.0  main   2024-03-27 22:31:17     
innounp  0.50    main   2024-03-27 22:31:53     
pipx     1.5.0   main   2024-04-02 04:54:43     
wingetui 3.0.1   extras 2024-03-27 22:32:29     
zeal     0.7.0   extras 2024-03-27 22:33:06     
[19-Apr-24 1:36:37 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:37 PM] Scoop ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop list
Installed apps:
Name     Version Source Updated             Info
----     ------- ------ -------             ----
7zip     23.01   main   2024-03-27 22:30:54     
git      2.44.0  main   2024-03-27 22:31:17     
innounp  0.50    main   2024-03-27 22:31:53     
pipx     1.5.0   main   2024-04-02 04:54:43     
wingetui 3.0.1   extras 2024-03-27 22:32:29     
zeal     0.7.0   extras 2024-03-27 22:33:06     
[19-Apr-24 1:36:37 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:38 PM] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-PSRepository
Name                      InstallationPolicy   SourceLocation                                                          
----                      ------------------   --------------                                                          
PSGallery                 Untrusted            https://www.powershellgallery.com/api/v2                                
[19-Apr-24 1:36:38 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:38 PM] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  list
Chocolatey v2.2.2
crossftp 1.96.4
dontsleep 9.47.0
dontsleep.install 9.47.0
filezilla 3.66.5
Gow 0.8.0
lxrunoffline 3.5.0
nano 7.2.36
nano-win 7.2.36
winaero-tweaker 1.55.0
9 packages installed.
[19-Apr-24 1:36:38 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:41 PM] Chocolatey ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\AppData\Local\Programs\WingetUI\choco-cli\choco.exe
█  Arguments:  outdated
Chocolatey v2.2.2
Outdated Packages
 Output is package name | current version | available version | pinned?
filezilla|3.66.5|3.67.0|false
Chocolatey has determined 1 package(s) are outdated. 
[19-Apr-24 1:36:41 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:41 PM] Scoop ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -ExecutionPolicy Bypass -Command scoop status
WARN  Scoop out of date. Run 'scoop update' to get the latest changes.
[19-Apr-24 1:36:41 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:41 PM] PowerShell ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Windows\system32\windowspowershell\v1.0\powershell.exe
█  Arguments:  -NoProfile -Command Get-InstalledModule
Version    Name                                Repository           Description                                        
-------    ----                                ----------           -----------                                        
2.1.0      Sudo                                PSGallery            Use functionality similar to sudo in PowerShell....
[19-Apr-24 1:36:41 PM] Exit Code: 0
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█▀▀▀▀▀▀▀▀▀ [19-Apr-24 1:36:41 PM] Winget ▀▀▀▀▀▀▀▀▀▀▀
█  Executable: C:\Users\adria\scoop\apps\wingetui\current\PackageEngine\Managers\winget-cli_x64\winget.exe
```
Truncated cause github says it's too long
```


### Relevant information

_No response_

### Screenshots and videos

![image](https://github.com/marticliment/WingetUI/assets/11292378/05906995-2fb1-4eac-b023-a2a63dd6fdad)

**Comment by essenciary** [comment] 2024-04-19 17:19
It installs the update. But when I restart the app, again, it shows the update notification.

**Comment by marticliment** [comment] 2024-04-19 22:06
Are you running any antivirus that could be interfiering with the update process?

**Comment by essenciary** [comment] 2024-04-22 11:20
Just the default windows security. 

Also, potentially unrelated, but some updates keep coming back. Ex, I've successfully updated Chrome, the Visual C++ redistributable packages and the NVIDIA CUDA Toolkit, but they keep showing up (7zip fails to be updated with error). 

![image](https://github.com/marticliment/WingetUI/assets/11292378/1f4448ab-22f6-483d-9dbc-677d49e85f56)

**Comment by marticliment** [comment] 2024-04-22 15:58
This is a bug with WinGet, please right-click the faulting packages -> skip this version

**Comment by marticliment** [comment] 2024-04-22 18:05
No

**Comment by CoolSpy3** [comment] 2024-04-26 05:59
I was running into a similar bug, so I did some investigating.

**Short:**
The auto-updater doesn't work when WingetUI is installed via scoop (and possably chocolatey).

**Long:**
It looks like when you click the update button in Winget, Winget downloads an installer which installs Winget to either `%LOCALAPPDATA%/Programs/` if you select "Current User" or I'm assuming  one of the `Program Files` directories if you select all users. This likely works for users who installed WingetUI via the installer.

The problem is that I originally installed Winget using scoop, so the scoop version remained unupdated. This led to me having two Winget installs, so the app would show as either version 3.0.1 or 3.0.2 depending on which version got launched.

I worked around the issue by running `scoop update wingetui` and deleting the other install.

**Notes:**
You say that you attempted to update using the installer from GitHub, but if you originally installed via a different method and did not uninstall WingetUI prior to using the installer, the installer would just have the effect mentioned above.

This does not explain the crashing you are experiencing, so that may be a different bug.

Of course, if you do not have a scoop/chocolatey installation, and this is unrelated, let me know and I will report this in a new issue.

**Comment by essenciary** [comment] 2024-04-26 09:22
@CoolSpy3 Thanks for your reply. You're right. 
WingetUI path: `C:\Users\adria\scoop\apps\wingetui\current\WingetUI.exe`
Scoop update: 
```
Scoop was updated successfully!
wingetui: 3.0.1 -> 3.0.2
Updating one outdated app:
Updating 'wingetui' (3.0.1 -> 3.0.2)
Downloading new version
WingetUI.Installer.exe (76.0 MB) [==============================================================================================================================] 100%
Checking hash of WingetUI.Installer.exe ... ok.
Uninstalling 'wingetui' (3.0.1)
Unlinking ~\scoop\apps\wingetui\current
Installing 'wingetui' (3.0.2) [64bit] from extras bucket
Loading WingetUI.Installer.exe from cache
Extracting WingetUI.Installer.exe ... done.
Linking ~\scoop\apps\wingetui\current => ~\scoop\apps\wingetui\3.0.2
Creating shortcut for WingetUI (WingetUI.exe)
'wingetui' (3.0.2) was installed successfully!
```

Now WingetUI no longer shows the update banner. 

So then: 
a) why does not WingetUI scoop update itself? Scoop is enabled. 
![image](https://github.com/marticliment/WingetUI/assets/11292378/be5184cb-3cd2-4cb8-93e9-0d6cfe264d0c)
b) why does not WingetUI show in Scoop as a source for itself? 
![image](https://github.com/marticliment/WingetUI/assets/11292378/be90b0f6-5b53-4b2a-a927-8a132d66886e)

**Comment by essenciary** [comment] 2024-04-26 09:27
It doesn't seem to use other enabled packages either, for ex `pip`: 
https://xon.sh/ default install is via pip. 
![image](https://github.com/marticliment/WingetUI/assets/11292378/42865146-2e2b-4ff3-a588-fef19f11c42c)

```
~ which pip                                                                                                                         in cmd at 11:26:48
C:\Users\adria\.pyenv\pyenv-win\shims\pip
```

**Comment by marticliment** [comment] 2024-04-26 13:36
I will investigate this

**Comment by essenciary** [comment] 2024-04-27 09:06
@marticliment just wanted to say thanks for the great software, it's very powerful and productive and I really enjoy it. 
We're also building OSS in Barcelona @ https://genieframework.com/ and I know how rewarding but also how very challenging it can be at times. Congrats and maybe we'll meet for a coffee someday.

**Comment by CoolSpy3** [comment] 2024-10-20 07:48
Update: As of v3.1.1, I am seeing the `wingetui` package show up as a scoop update, however, it cannot be updated through UniGetUI because UniGetUI is running. I am also not seeing the autoupdater to v3.1.2.

**Comment by marticliment** [comment] 2024-10-20 08:19
The autoupdater hasn't been triggered yet, this has been done on purpose. Autoupdate will begin in the following hours

**Comment by marticliment** [comment] 2024-10-24 22:09
This issue will be fixed once https://github.com/ScoopInstaller/Nonportable/pull/362 is merged

**Closed by marticliment** 2024-10-24 22:09 UTC
Labels: bug, ready-to-go, important
