### ISSUE TITLE
[BUG] 3.1.0 stable wants to update to 3.1.0-beta1

### ISSUE THREAD

**Issue by redactedscribe** [marticliment/UniGetUI#2399] opened 2024-07-03 09:40 UTC
### Please confirm these before moving forward

- [X] I have searched for my issue and have not found a work-in-progress/duplicate/resolved issue.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).
- [X] I have checked the [FAQ](https://github.com/marticliment/WingetUI#frequently-asked-questions) section for solutions.
- [X] This issue is about a bug (if it is not, please use the [correct template](https://github.com/marticliment/WingetUI/issues/new/choose)).

### UniGetUI Version

3.1.0

### Windows version, edition and architecture

Windows 11 Pro

### Describe your issue

The stable release of 3.1.0 has an update for 3.1.0-beta1 even though the beta1 release is older.

### Steps to reproduce the issue

Install 3.1.0 and check for updates.

### UniGetUI Log

```text
-
```

### Package Managers Logs

```text
-
```

### Relevant information

Not sure why the Source column does not contain a label next to the icon. I see a couple other Scoop packages which also have this problem, e.g. Signal.

### Screenshots and videos

![WingetUI_2024-07-03_12-38-35](https://github.com/marticliment/UniGetUI/assets/25013746/4825c74b-d3f5-48bf-9ec9-5f8f258974b0)

**Comment by vikingnope** [comment] 2024-07-03 09:42
You will have to wait for the new package to be uploaded for wingetui on winget.

**Comment by marticliment** [comment] 2024-07-03 09:42
Until 3.1.0 gets pubblished on WinGet this will happen. I don't know why that happens, I have just realized it today

**Comment by vikingnope** [comment] 2024-07-03 09:43
> Until 3.1.0 gets published on WinGet this will happen. I don't know why that happens, I have just realized it today

It is probably happening due to the DisplayName listed in the Pre-Release manifest and it is therefore being detected.

**Comment by BrianG61UK** [comment] 2024-07-03 11:46
Everything seems to work out well if you right click that update that is actually a downgrade and choose "Skip this version".

**Comment by hueldoeu** [comment] 2024-07-03 11:48
happened here too. was watching a zoom conference and suddenly POOF "unigetui (formerly wingetui) wants to get permission to be opened" for installing, clicked yes, continued watching ZOOM and since then i see this winget upgrade (skipped it in unigetui):
![image](https://github.com/marticliment/UniGetUI/assets/11273667/ce6b23df-5db9-448a-a483-a7d8c394ae4e)

UniGetUI (formerly WingetUI) SomePythonThings.WingetUIStore.Pre-release 3.1.0   3.1.0-beta1 winget

checked the version of the freshly updates unigetui
![image](https://github.com/marticliment/UniGetUI/assets/11273667/ca5252e6-c017-4d28-902d-6b1d6d925e64)

**Comment by vikingnope** [comment] 2024-07-03 11:57
> happened here too. was watching a zoom conference and suddenly POOF "unigetui (formerly wingetui) wants to get permission to be opened" for installing, clicked yes, continued watching ZOOM and since then i see this winget upgrade (skipped it in unigetui): ![image](https://private-user-images.githubusercontent.com/11273667/345408483-ce6b23df-5db9-448a-a483-a7d8c394ae4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDgxMDYsIm5iZiI6MTcyMDAwNzgwNiwicGF0aCI6Ii8xMTI3MzY2Ny8zNDU0MDg0ODMtY2U2YjIzZGYtNWRiOS00NDhhLWE0ODMtYTdkOGMzOTRhZTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExNTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZWU4MTk1ODEwNzNiZWVhOTYzY2U0NTY3YTdkNWYxODMwYjJhMDgwZjVlM2RiNDQ5YzQ4MDI5MzRjNjA1ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.17eyrk40qay_NQndYhIKsJLSseticFvQ-TVHgqyrsNg)
> 
> UniGetUI (formerly WingetUI) SomePythonThings.WingetUIStore.Pre-release 3.1.0 3.1.0-beta1 winget
> 
> checked the version of the freshly updates unigetui ![image](https://private-user-images.githubusercontent.com/11273667/345408702-ca5252e6-c017-4d28-902d-6b1d6d925e64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDgxMDYsIm5iZiI6MTcyMDAwNzgwNiwicGF0aCI6Ii8xMTI3MzY2Ny8zNDU0MDg3MDItY2E1MjUyZTYtYzAxNy00ZDI4LTkwMmQtNmIxZDZkOTI1ZTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExNTY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZGIyMWViOGUwMzgwYjdlNzdjOWNkYmI5N2I3ZmYwZWVjMTkzMGMzNTkxOTdlNzgzMzVjNTYwMjkxOWViMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WxaZ94Xv5Q-NJClch0NcLN2dGVKjGFGXLwCJzOSes0k)

Read what was said above, known issue.

**Comment by BrianG61UK** [comment] 2024-07-03 13:56
> Everything seems to work out well if you right click that update that is actually a downgrade and choose "Skip this version".

Correction. I got a very similar error when it tried to update Ppowertoys to 0.82.0 ! I had to download it and update manuaklly. I will investigate later - too busy right now.

**Comment by EckeD** [comment] 2024-07-04 08:17
Just to add that info here: same issue now happens with beta2 - is also found as an update.
So again: right-click and "Skip this version" :)

**Comment by vikingnope** [comment] 2024-07-04 08:22
> Just to add that info here: same issue now happens with beta2 - is also found as an update. So again: right-click and "Skip this version" :)

Known issue, 3.1.0 manifest has not been merged yet, hopefully will be merged by tonight, some patience pls

**Comment by xsm2** [comment] 2024-07-05 10:22
Mine it's trying to update to beta2, my source it's scoop though
![imagen](https://github.com/marticliment/UniGetUI/assets/32161135/093b90a4-b6db-411c-9f35-d100825ab983)

**Comment by marticliment** [comment] 2024-07-05 10:50
I don't know who is maintaining the scoop manifest, so I can't help about that

**Comment by marticliment** [comment] 2024-07-05 11:13
> It shouldn't be trying to update to beta2, only 3.1.0 is offered (maybe it's a UI bug?): https://github.com/ScoopInstaller/Extras/blob/master/bucket/wingetui.json

It should not, please run the command `scoop status` on a cmd window

**Comment by marticliment** [comment] 2024-07-05 11:18
> > It shouldn't be trying to update to beta2, only 3.1.0 is offered (maybe it's a UI bug?): https://github.com/ScoopInstaller/Extras/blob/master/bucket/wingetui.json
> 
> It should not, please run the command `scoop status` on a cmd window

Please try reolading the Package Lists. Does it still say scoop? I saw now from the image that the icon is the WinGet icon

**Comment by xsm2** [comment] 2024-07-05 11:25
> > It shouldn't be trying to update to beta2, only 3.1.0 is offered (maybe it's a UI bug?): https://github.com/ScoopInstaller/Extras/blob/master/bucket/wingetui.json
> 
> It should not, please run the command `scoop status` on a cmd window

![imagen](https://github.com/marticliment/UniGetUI/assets/32161135/97c3d477-0273-48cd-83d7-0ff1ee9cd63d)

**Comment by Enzo-Nunes** [comment] 2024-07-05 11:31
> I have the same issue, it is trying to update to beta2 from winget sources
> 
> ![UniGetUI updateable from 3.1.0 to 3.1.0-beta2](https://private-user-images.githubusercontent.com/96084563/346105676-c40ad53a-f475-49ff-8279-3c881bb5af53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzg5NTAsIm5iZiI6MTcyMDE3ODY1MCwicGF0aCI6Ii85NjA4NDU2My8zNDYxMDU2NzYtYzQwYWQ1M2EtZjQ3NS00OWZmLTgyNzktM2M4ODFiYjVhZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDExMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNmM1OGVlMDJlZTZhMDdmNTg1MTMzMjQyZTQ0NTFhY2I1NzVhOGNkZDM3OWM5ZDlkMjdmMzFjNWE3YTI1YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dOvdcNRmZSyQHO4wHbQpcO6ziP5yvmDeBblTXrCzTf0)
> 
> same thing when running `winget update` in a cmd window
> 
> ```
> Name                         Id                                         Version Available   Source
> --------------------------------------------------------------------------------------------------
> UniGetUI (formerly WingetUI) SomePythonThings.WingetUIStore.Pre-release 3.1.0   3.1.0-beta2 winget
> ```
> 
> Using winget v1.8.1791

I have the same issue, beta-2 shows up in both the UI and cmd `winget update`. Update fails with both, regardless.

**Comment by vikingnope** [comment] 2024-07-05 14:50
To anyone who is not understanding the situation here is the reason why you are still getting the update to 3.1.0-beta2

- The manifest for UniGetUI 3.1.0 has not been posted yet due to some errors with both the validation pipeline and a bug with the installer.
- It is currently telling you guys to "update" to the Pre-Release versions. This is due to those manifests having a flag which points to the new Display Name (i.e. UniGetUI (formerly WinGetUI) shown in the Apps and Features page, and since the latest non pre-release version is still using the old name (i.e. WinGetUI) it is telling you to "upgrade" to the pre-release version.

Anyone who has source showing as Winget:winget these are the reasons. For the one off case which has scoop on the side I do not know what the issue is, seems to be conflicting with Winget for some reason because even the package identifier is the same as winget.

**Comment by marticliment** [comment] 2024-07-05 14:55
The issue with scoop seems to be a visual glitch. The Id and the icon are both from WinGet

**Comment by vikingnope** [comment] 2024-07-05 19:58
This issue should now be solved, kindly confirm and if so close the issue.

**Comment by marticliment** [comment] 2024-07-05 20:09
It has been solved. The update is not shown anymore

**Closed by marticliment** 2024-07-05 20:09 UTC
Labels: bug

**Comment by vikingnope** [comment] 2024-07-05 20:13
> Thank you for the help @vikingnope

No problem, although I do urge you to try and find a solution if possible to the dependencies and install script being run separately to try and run them in one go. Like that new manifests will be added quicker due to verification passing all the tests unless other issues are found. :)

**Comment by hueldoeu** [comment] 2024-07-05 20:29
unigetui is one nice piece of software :)

**Comment by hueldoeu** [comment] 2024-10-22 14:50
i just wanted to say that i upgraded a PC from windows 10 to windows 11, although the CPU was too old and installed several drivers for acteon sopix2, but the sensor (sopix2 is an x-ray sensor) doesn't work and i think the driver-installers changed the  Microsoft.VCRedist.2015+.x86 or the Microsoft.VCRedist.2015+.x64 package a lot. or maybe i did a cmd => winget upgrade on windows 11. then i downgraded from windows 11 to windows 10 and had problems with Microsoft.VCRedist.2015+.xXX. couldn't update it or something else. then some unigetUI version couldn't be installed and i used cmd => winget upgrade on this particular PC for some time until i've discovered winget install --exact --id MartiCliment.UniGetUI --source winget

worked like a charme.
