### ISSUE TITLE
[CRASH] (NamedParameterNotFound,Update-Module)

### ISSUE THREAD

**Issue by Jkegithub** [marticliment/UniGetUI#2934] opened 2024-11-04 09:39 UTC
### Please confirm these before moving forward.

- [X] I have tried deleting a folder named `UniGetUI` under `%UserProfile%\AppData\Local\UniGetUI`.
- [X] I have tried reinstalling UniGetUI.
- [X] I have tested that this issue has not been fixed in the latest [(beta or stable) release](https://github.com/marticliment/WingetUI/releases/).

### Describe your crash

Starting package update operation for package id=Microsoft.WinGet.Client with Manager name=PowerShell
Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
Process Executable     : C:\WINDOWS\system32\windowspowershell\v1.0\powershell.exe
Process Call Arguments :  -NoProfile -Command Update-Module -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope CurrentUser
Working Directory      : C:\Users\juerg
Process Start Time     : 04.11.2024 10:33:28
Update-Module : Es wurde kein Parameter gefunden, der dem Parameternamen "Scope" entspricht.
In Zeile:1 Zeichen:68
+ ... e -Name Microsoft.WinGet.Client -Confirm:$false -Force -Scope Current ...
+                                                            ~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Update-Module], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Update-Module
Process Exit Code      : 1
Process End Time       : 04.11.2024 10:33:29

### More details

continuuing

**Comment by marticliment** [comment] 2024-11-04 13:39
Duplicate of #2814

**Closed by marticliment** 2024-11-04 13:39 UTC
Labels: bug, important
