### ISSUE TITLE
[ENHANCEMENT] Ability to load a custom tab on startup

### ISSUE THREAD

**Issue by EDM115** [marticliment/UniGetUI#2622] opened 2024-08-11 17:55 UTC
### Please confirm these before moving forward.

- [X] I have searched for my feature proposal and have not found a work-in-progress/duplicate/resolved/discarded issue.
- [X] This improvement refers to an existing feature. If you want to suggest a new feature, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=new-feature&projects=&template=feature-request.yml&title=%5BFEATURE+REQUEST%5D+%28Enter+your+description+here%29).
- [X] This improvement is not a bug. If you want to report a bug, please use [this template](https://github.com/marticliment/WingetUI/issues/new?assignees=marticliment&labels=bug&projects=&template=bug-issue.yml&title=%5BBUG%5D+%28Enter+your+description+here%29).

### Describe the improvement

You could add a setting which allows us to select which tab is opened at app startup (Discover Packages, Software Updates, Installed Packages, Package Bundles)

### Describe how this improvement could help users

This could be useful for users like me who uses UniGetUI solely for the updates and never used the 3 other tabs

**Comment by marticliment** [comment] 2024-08-11 21:00
duplicate of #470

**Closed by marticliment** 2024-08-11 21:00 UTC
Labels: enhancement
